### ISSUE TITLE
No dark mode pages

### ISSUE THREAD

**Issue by hani4k** [bundui/cakeadmin#4]
Hi, could you please tell me where's the dark mode implementation?

**Comment by laborasyon** [comment]
@hani4k 

Dark mode is not fully available right now, but if you still want to use it, try this code.

<body class="dark">

Note: Dark mode will be improved in future updates.

**Comment by hani4k** [comment]
Hi,

Thanks for the code. I've already tried using this class because I was
using the Vetra template before, but it's kind of broken on this template.

Thanks,
Hani Mohamed Bioud m

**Comment by bundui** [comment]
The problems were solved with the latest changes.
